name: sbom-scanner


on:
  push:
    branches:
      - main
  pull_request:

jobs:
  sbom-scan:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Install Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # Step 3: Install Grype
      - name: Install Grype
        run: |
          curl -sSfL https://raw.githubusercontent.com/anchore/grype/main/install.sh | sh -s -- -b /usr/local/bin

      # Generate a dummy SBOM for demonstration purposes
      - name: Generate Dummy SBOM
        run: |
          mkdir -p dummy-project
          echo "placeholder content" > dummy-project/placeholder.txt
          curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh -s -- -b /usr/local/bin
          syft dummy-project -o json > dummy-project-sbom.json

      # Run the scan.py script
      - name: Run Grype Scan
        run: |
          python3 scan.py --repo-name dummy-project --sbom-path dummy-project-sbom.json --report-dir ./reports

      # Step 6: Upload the Grype report as an artifact
      - name: Upload Grype Report
        uses: actions/upload-artifact@v3
        with:
          name: grype-report
          path: ./reports/